repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.12.1'
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies: ["tomli"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.16.1'
  hooks:
  - id: mypy
    additional_dependencies: ["pytest", "hypothesis"]
