name: Build and upload package

on:
  push:
    branches:
    - main
  release:
    types:
    - published
  workflow_dispatch:

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  build:
    name: Build & Verify package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - run: python -m pip install --upgrade build twine
    - run: python -m build
    - run: twine check --strict dist/*
    - uses: actions/upload-artifact@v4
      with:
        name: Packages
        path: dist/

  pypi-publish:
    name: Publish released package to pypi.org
    runs-on: ubuntu-latest
    needs: build
    if: github.event.action == 'published'
    environment:
      name: pypi
      url: https://pypi.org/p/dvc
    permissions:
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
